Repository virtualsatellite/VirtualSatellite4-FDIR, pull requests merged in 2019-08, with the labels that each got.

#84 Feature/Task 18 Add Minimization
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/model/RecoveryAutomatonTest.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/ra/RecoveryAutomatonFeatureProvider.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/ra/features/recoveryAutomata/MinimizeRAFeature.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/snippet/UiSnippetSectionRecoveryAutomaton.java
  de.dlr.sc.virsat.model.extension.fdir/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/RecoveryAutomaton.java
Labels: ui

#82 Feature/task 53 implement symmtery red
  .travis.yml
  de.dlr.sc.virsat.fdir.target/tmodel-src/virsat_fdir_development.tmodel
  de.dlr.sc.virsat.fdir.target/virsat_fdir_integration.target
  de.dlr.sc.virsat.model.extension.fdir.test/resources/galileo/and2OrAnd2OrAnd2Symmetric.dft
  de.dlr.sc.virsat.model.extension.fdir.test/resources/galileo/and2OrAnd2SharedSymmetric.dft
  de.dlr.sc.virsat.model.extension.fdir.test/resources/galileo/and2OrAnd2Symmetric.dft
  de.dlr.sc.virsat.model.extension.fdir.test/resources/galileo/and2Symmetric.dft
  de.dlr.sc.virsat.model.extension.fdir.test/resources/galileo/and2and2Symmetric.dft
  de.dlr.sc.virsat.model.extension.fdir.test/resources/galileo/and3Symmetric.dft
  de.dlr.sc.virsat.model.extension.fdir.test/resources/galileo/beOrAnd2Symmetric.dft
  de.dlr.sc.virsat.model.extension.fdir.test/resources/galileo/ftpp4.dft
  de.dlr.sc.virsat.model.extension.fdir.test/resources/galileo/pand4.dft
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/DFT2MAConverterTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/FaultTreeSymmetryCheckerTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/test/AllTests.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/DFT2MAConverter.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/DFTState.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/FaultTreeSymmetryChecker.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/semantics/FaultSemantics.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/DFTEvaluator.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/FaultTreeEvaluator.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/BasicEvent.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/FaultTreeNode.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/util/FaultTreeHolder.java
Labels: feature

#86 Feature/Task 83 Create Statistics
  bash/deploy_sourceforge.sh
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/markov/modelchecker/IMarkovModelChecker.java
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/markov/modelchecker/MarkovModelChecker.java
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/markov/modelchecker/ModelCheckingStatistics.java
  de.dlr.sc.virsat.fdir.storm/src/de/dlr/sc/virsat/fdir/storm/runner/StormModelChecker.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/DFT2MAConversionStatistics.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/DFT2MAConverter.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/DFTEvaluationStatistics.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/DFTEvaluator.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/recovery/minimizer/ARecoveryAutomatonMinimizer.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/recovery/minimizer/CleanMinimizer.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/recovery/minimizer/ComposedMinimizer.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/recovery/minimizer/FinalStateMinimizer.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/recovery/minimizer/MinimizationStatistics.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/recovery/minimizer/OrthogonalPartitionRefinementMinimizer.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/recovery/minimizer/PartitionRefinementMinimizer.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/synthesizer/ASynthesizer.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/synthesizer/SynthesisStatistics.java
Labels: quality

#89 Feature/Task 56 Recovery Automaton diagram doesnt request for update
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/ra/RecoveryAutomatonFeatureProvider.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/ra/features/recoveryAutomata/MinimizeRAFeature.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/ra/features/states/StateAddFeature.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/ra/features/states/StateUpdateFeature.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/ra/features/transitions/TransitionAddFeature.java
Labels: bug

#91 Feature/Task 90 Introduce canonic recovery state
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/DFTState.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/recovery/RecoveryStrategy.java
Labels: feature

#92 Feature/task 88 reconsider ft x ra con
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/markov/modelchecker/MarkovModelChecker.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/synthesizer/BasicSynthesizerTest.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/DFT2MAConverter.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/po/PONDDFTSemantics.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/po/PONDSPARESemantics.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/semantics/DFTSemantics.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/semantics/NDSPARESemantics.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/semantics/StandardSPARESemantics.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/ClaimAction.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/recovery/RecoveryStrategy.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/util/RecoveryAutomatonHolder.java
Labels: bug

#95 Feature/Task 94 Use Statistics object for assertions / experiments
  de.dlr.sc.virsat.model.extension.fdir.experiments/src/de/dlr/sc/virsat/model/extension/fdir/experiments/ASynthesizerExperiment.java
  de.dlr.sc.virsat.model.extension.fdir.experiments/src/de/dlr/sc/virsat/model/extension/fdir/experiments/aiaa/AIAA2018Experiments.java
  de.dlr.sc.virsat.model.extension.fdir.experiments/src/de/dlr/sc/virsat/model/extension/fdir/experiments/ftscs/FTSCS2018Experiments.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/DFT2MAConverterTest.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/DFTEvaluator.java
Labels: quality

#98 Added setBEOptimizationOn - (Task #97)
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/modularizer/ModularizerTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/synthesizer/BasicSynthesizerTest.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/modularizer/Modularizer.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/synthesizer/ASynthesizer.java
Labels: feature, quality

#102 Feature/task 80 rise2019 experiments b
  de.dlr.sc.virsat.fdir.target/virsat_fdir_development.target
  de.dlr.sc.virsat.model.extension.fdir.experiments/resources/rise/2019/ahrs/ahrs1.dft
  de.dlr.sc.virsat.model.extension.fdir.experiments/resources/rise/2019/ahrs/ahrs2.dft
  de.dlr.sc.virsat.model.extension.fdir.experiments/resources/rise/2019/cm/cm1.dft
  de.dlr.sc.virsat.model.extension.fdir.experiments/resources/rise/2019/cm/cm2.dft
  de.dlr.sc.virsat.model.extension.fdir.experiments/resources/rise/2019/cm/cm5.dft
  de.dlr.sc.virsat.model.extension.fdir.experiments/resources/rise/2019/cm/cm_simple.dft
  de.dlr.sc.virsat.model.extension.fdir.experiments/resources/rise/2019/hecs/hecs1-1.dft
  de.dlr.sc.virsat.model.extension.fdir.experiments/resources/rise/2019/hecs/hecs2-1.dft
  de.dlr.sc.virsat.model.extension.fdir.experiments/resources/rise/2019/hecs/hecs3-1.dft
  de.dlr.sc.virsat.model.extension.fdir.experiments/resources/rise/2019/hecs/hecs4-1.dft
  de.dlr.sc.virsat.model.extension.fdir.experiments/resources/rise/2019/hecs/hecs5-1.dft
  de.dlr.sc.virsat.model.extension.fdir.experiments/resources/rise/2019/hecs/hecs6-1.dft
  de.dlr.sc.virsat.model.extension.fdir.experiments/resources/rise/2019/hecs/hecs7-1.dft
  de.dlr.sc.virsat.model.extension.fdir.experiments/resources/rise/2019/hecs/hecs8-1.dft
  de.dlr.sc.virsat.model.extension.fdir.experiments/resources/rise/2019/mas/mas1.dft
  de.dlr.sc.virsat.model.extension.fdir.experiments/resources/rise/2019/mas/mas2.dft
  de.dlr.sc.virsat.model.extension.fdir.experiments/resources/rise/2019/rc/bigTree_213BEs.dft
  de.dlr.sc.virsat.model.extension.fdir.experiments/resources/rise/2019/rc/bigTree_253BEs.dft
  de.dlr.sc.virsat.model.extension.fdir.experiments/resources/rise/2019/rc/rc-1-1-sc.dft
  de.dlr.sc.virsat.model.extension.fdir.experiments/resources/rise/2019/rc/rc-1-2-hc.dft
  de.dlr.sc.virsat.model.extension.fdir.experiments/resources/rise/2019/rc/rc-1-3-hc.dft
  de.dlr.sc.virsat.model.extension.fdir.experiments/resources/rise/2019/rc/rc-1-4-hc.dft
  de.dlr.sc.virsat.model.extension.fdir.experiments/resources/rise/2019/rc/rc-1-4-sc.dft
  de.dlr.sc.virsat.model.extension.fdir.experiments/resources/rise/2019/rc/rc-1-5-hc.dft
  de.dlr.sc.virsat.model.extension.fdir.experiments/resources/rise/2019/rc/rc-10-1-hc.dft
  de.dlr.sc.virsat.model.extension.fdir.experiments/resources/rise/2019/rc/rc-10-1-sc.dft
  de.dlr.sc.virsat.model.extension.fdir.experiments/resources/rise/2019/rc/rc-10-10-hc.dft
  de.dlr.sc.virsat.model.extension.fdir.experiments/resources/rise/2019/rc/rc-15-1-hc.dft
  de.dlr.sc.virsat.model.extension.fdir.experiments/resources/rise/2019/rc/rc-15-15-hc.dft
  de.dlr.sc.virsat.model.extension.fdir.experiments/resources/rise/2019/rc/rc-20-1-hc.dft
  de.dlr.sc.virsat.model.extension.fdir.experiments/resources/rise/2019/rc/rc-20-20-hc.dft
  de.dlr.sc.virsat.model.extension.fdir.experiments/resources/rise/2019/vgs/vgs1.dft
  de.dlr.sc.virsat.model.extension.fdir.experiments/resources/rise/2019/vgs/vgs2.dft
  de.dlr.sc.virsat.model.extension.fdir.experiments/resources/rise/2019/vgs/vgs3.dft
  de.dlr.sc.virsat.model.extension.fdir.experiments/resources/rise/2019/vgs/vgs4.dft
  de.dlr.sc.virsat.model.extension.fdir.experiments/resources/rise/2019/vgs/vgs5.dft
  de.dlr.sc.virsat.model.extension.fdir.experiments/resources/rise/2019/vgs/vgs6.dft
  de.dlr.sc.virsat.model.extension.fdir.experiments/resources/rise/2019/vgs/vgs7.dft
  de.dlr.sc.virsat.model.extension.fdir.experiments/resources/rise/2019/vgs/vgs8.dft
  de.dlr.sc.virsat.model.extension.fdir.experiments/src/de/dlr/sc/virsat/model/extension/fdir/experiments/ASynthesizerExperiment.java
  de.dlr.sc.virsat.model.extension.fdir.experiments/src/de/dlr/sc/virsat/model/extension/fdir/experiments/ftscs/SCP2019Experiments.java
  de.dlr.sc.virsat.model.extension.fdir.experiments/src/de/dlr/sc/virsat/model/extension/fdir/experiments/rise/BenchmarkExperiments.java
  de.dlr.sc.virsat.model.extension.fdir.experiments/src/de/dlr/sc/virsat/model/extension/fdir/experiments/rise/BenchmarkExperimentsWithoutModularization.java
  de.dlr.sc.virsat.model.extension.fdir.experiments/src/de/dlr/sc/virsat/model/extension/fdir/experiments/rise/DemoExperiments.java
  de.dlr.sc.virsat.model.extension.fdir.test/resources/galileo/ahrs2.dft
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/modularizer/ModularizerTest.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/recovery/ParallelComposer.java
Labels: quality

#103 Feature/Task 93 Approximate MTTF using composed Reliability
  de.dlr.sc.virsat.fdir.core.test/src/de/dlr/sc/virsat/fdir/core/markov/modelchecker/ModelCheckingResultTest.java
  de.dlr.sc.virsat.fdir.core.test/src/de/dlr/sc/virsat/fdir/core/test/AllTests.java
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/markov/modelchecker/IMarkovModelChecker.java
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/markov/modelchecker/MarkovModelChecker.java
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/markov/modelchecker/ModelCheckingResult.java
  de.dlr.sc.virsat.fdir.storm.test/src/de/dlr/sc/virsat/fdir/storm/runner/StormRunnerTest.java
  de.dlr.sc.virsat.fdir.storm.test/src/de/dlr/sc/virsat/fdir/storm/test/AllTests.java
  de.dlr.sc.virsat.fdir.storm/src/de/dlr/sc/virsat/fdir/storm/runner/StormModelChecker.java
  de.dlr.sc.virsat.fdir.storm/src/de/dlr/sc/virsat/fdir/storm/runner/StormRunner.java
  de.dlr.sc.virsat.model.extension.fdir.test/resources/galileo/rc1.dft
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/DFT2MAConverterTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/test/ATestCase.java
  de.dlr.sc.virsat.model.extension.fdir/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2dft/DFT2BasicDFTConverter.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/DFT2MAConverter.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/DFTState.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/FaultTreeSymmetryChecker.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/DFTEvaluator.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/DFTMetricsComposer.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/FaultTreeEvaluator.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/IFaultTreeEvaluator.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/StormEvaluator.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/modularizer/FaultTreeNodePlus.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/modularizer/Modularizer.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/modularizer/Module.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/synthesizer/ASynthesizer.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/util/FaultTreeHolder.java
Labels: feature

#107 Recreated branch - (Task #19)
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/model/RecoveryAutomatonTest.java
  de.dlr.sc.virsat.model.extension.fdir.ui/plugin.xml
  de.dlr.sc.virsat.model.extension.fdir.ui/src-gen/de/dlr/sc/virsat/model/extension/fdir/ui/command/ACreateAddArrayElementAvailabilityCurveCommand.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src-gen/de/dlr/sc/virsat/model/extension/fdir/ui/snippet/AUiSnippetTableAvailabilityAnalysisAvailabilityCurve.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/command/CreateAddArrayElementAvailabilityCurveCommand.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/snippet/UiSnippetSectionAvailabilityAnalysis.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/snippet/UiSnippetSectionReliabilityAnalysis.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/snippet/UiSnippetTableAvailabilityAnalysisAvailabilityCurve.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/snippet/UiSnippetTableAvailabilityAnalysisPointAvailabilityCurve.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/snippet/UiSnippetTableReliabilityAnalysis.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/snippet/UiSnippetTableReliabilityAnalysisReliabilityCurve.java
  de.dlr.sc.virsat.model.extension.fdir/concept/concept.concept
  de.dlr.sc.virsat.model.extension.fdir/concept/concept.xmi
  de.dlr.sc.virsat.model.extension.fdir/concept/concept_v1_1.xmi
  de.dlr.sc.virsat.model.extension.fdir/src-gen/de/dlr/sc/virsat/model/extension/fdir/model/AAvailabilityAnalysis.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/AvailabilityAnalysis.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/RecoveryAutomaton.java
Labels: quality, ui

#118 Feature/task 115 introduce metrics for
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/markov/modelchecker/MarkovModelChecker.java
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/markov/modelchecker/ModelCheckingResult.java
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/metrics/Availability.java
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/metrics/Detectability.java
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/metrics/FailLabelProvider.java
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/metrics/IDerivedMetric.java
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/metrics/IDerivedMetricVisitor.java
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/metrics/IMetric.java
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/metrics/MTTF.java
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/metrics/MeanTimeToDetection.java
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/metrics/SteadyStateAvailability.java
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/metrics/SteadyStateDetectability.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/DFTEvaluatorTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/StormEvaluatorTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/model/DetectabilityAnalysisTest.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/DFT2MAConverter.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/DFTEvaluator.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/DFTMetricsComposer.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/DFTModularization.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/FailNodeProvider.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/FaultTreeEvaluator.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/IFaultTreeEvaluator.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/StormDFTEvaluator.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/DetectabilityAnalysis.java
Labels: feature

#119 Feature/task 111 refine minium cut set
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/markov/modelchecker/MarkovModelChecker.java
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/metrics/AProbabilityCurve.java
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/metrics/Availability.java
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/metrics/Detectability.java
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/metrics/IQuantitativeMetric.java
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/metrics/Reliability.java
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/metrics/SteadyStateDetectability.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/DFTEvaluatorTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/model/AvailabilityAnalysisTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/model/MCSAnalysisTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/model/ReliabilityAnalysisTest.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src-gen/de/dlr/sc/virsat/model/extension/fdir/ui/command/ACreateAddArrayElementDetectionMeansCommand.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src-gen/de/dlr/sc/virsat/model/extension/fdir/ui/snippet/AUiSnippetTableCutSetDetectionMeans.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/command/CreateAddArrayElementDetectionMeansCommand.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/snippet/UiSnippetSectionMCSAnalysis.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/snippet/UiSnippetTableCutSetDetectionMeans.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/snippet/UiSnippetTableMCSAnalysisMinimumCutSetsCutSet.java
  de.dlr.sc.virsat.model.extension.fdir/concept/concept.concept
  de.dlr.sc.virsat.model.extension.fdir/concept/concept.xmi
  de.dlr.sc.virsat.model.extension.fdir/concept/concept_v1_1.xmi
  de.dlr.sc.virsat.model.extension.fdir/src-gen/de/dlr/sc/virsat/model/extension/fdir/model/AAvailabilityAnalysis.java
  de.dlr.sc.virsat.model.extension.fdir/src-gen/de/dlr/sc/virsat/model/extension/fdir/model/ACutSet.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/DFT2MAConverter.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/DFTEvaluator.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/DFTMetricsComposer.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/FailableBasicEventsProvider.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/FaultTreeEvaluator.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/IFaultTreeEvaluator.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/StormDFTEvaluator.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/AvailabilityAnalysis.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/CutSet.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/FMECA.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/FMECAEntry.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/MCSAnalysis.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/ReliabilityAnalysis.java
Labels: feature

#123 Feature/Task 116 Introduce UNKNOWN enum value
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/calculation/OpClassifyDLTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/calculation/OpClassifyPLTest.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/snippet/UiSnippetTableFMECAEntriesFMECAEntry.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/snippet/UiSnippetTableMCSAnalysisMinimumCutSetsCutSet.java
  de.dlr.sc.virsat.model.extension.fdir/concept/concept.concept
  de.dlr.sc.virsat.model.extension.fdir/concept/concept.xmi
  de.dlr.sc.virsat.model.extension.fdir/concept/concept_v1_1.xmi
  de.dlr.sc.virsat.model.extension.fdir/src-gen/de/dlr/sc/virsat/model/extension/fdir/model/ACutSet.java
  de.dlr.sc.virsat.model.extension.fdir/src-gen/de/dlr/sc/virsat/model/extension/fdir/model/AFMECAEntry.java
  de.dlr.sc.virsat.model.extension.fdir/src-gen/de/dlr/sc/virsat/model/extension/fdir/model/AFault.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/calculation/OpClassifyDL.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/calculation/OpClassifyPL.java
Labels: feature

#137 Added test case - (Task #136)
  de.dlr.sc.virsat.fdir.target/virsat_fdir_release.target
  de.dlr.sc.virsat.fdir.test.feature/feature.xml
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/trimmer/FaultTreeTrimmerTest.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/trimmer/FaultTreeTrimmer.java
Labels: feature, quality
