Repository virtualsatellite/VirtualSatellite4-FDIR, pull requests merged in 2019-09, with the labels that each got.

#135 Feature/task 125 improve benchmark exp
  de.dlr.sc.virsat.model.extension.fdir.experiments/resources/results/rise/2019/benchmarkExperimentsStatistics.txt
  de.dlr.sc.virsat.model.extension.fdir.experiments/resources/results/rise/2019/benchmarkExperimentsStatisticsWM.txt
  de.dlr.sc.virsat.model.extension.fdir.experiments/resources/rise/2019/ahrs/ahrs2.dft
  de.dlr.sc.virsat.model.extension.fdir.experiments/resources/rise/2019/experimentSet
  de.dlr.sc.virsat.model.extension.fdir.experiments/resources/rise/2019/experimentSetWM
  de.dlr.sc.virsat.model.extension.fdir.experiments/resources/rise/2019/rc/bigTree_213BEs.dft
  de.dlr.sc.virsat.model.extension.fdir.experiments/resources/rise/2019/rc/bigTree_253BEs.dft
  de.dlr.sc.virsat.model.extension.fdir.experiments/resources/rise/2019/rc/rc-10-10-hc.dft
  de.dlr.sc.virsat.model.extension.fdir.experiments/resources/rise/2019/rc/rc-15-15-hc.dft
  de.dlr.sc.virsat.model.extension.fdir.experiments/resources/rise/2019/rc/rc-20-20-hc.dft
  de.dlr.sc.virsat.model.extension.fdir.experiments/src/de/dlr/sc/virsat/model/extension/fdir/experiments/ASynthesizerExperiment.java
  de.dlr.sc.virsat.model.extension.fdir.experiments/src/de/dlr/sc/virsat/model/extension/fdir/experiments/rise/BenchmarkExperiments.java
  de.dlr.sc.virsat.model.extension.fdir.experiments/src/de/dlr/sc/virsat/model/extension/fdir/experiments/rise/BenchmarkExperimentsWithoutModularization.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/DFT2MAConverter.java
Labels: feature, quality

#143 Feature/task 142 deal with the new war
  de.dlr.sc.virsat.fdir.branding.ui/.settings/org.eclipse.pde.prefs
  de.dlr.sc.virsat.fdir.branding.ui/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.fdir.core.test/.settings/org.eclipse.pde.prefs
  de.dlr.sc.virsat.fdir.core.test/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.fdir.core/.settings/org.eclipse.pde.prefs
  de.dlr.sc.virsat.fdir.core/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.fdir.galileo.ide/.settings/org.eclipse.pde.prefs
  de.dlr.sc.virsat.fdir.galileo.ide/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.fdir.galileo.tests/.settings/org.eclipse.pde.prefs
  de.dlr.sc.virsat.fdir.galileo.tests/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.fdir.galileo.ui/.settings/org.eclipse.pde.prefs
  de.dlr.sc.virsat.fdir.galileo.ui/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.fdir.storm.test/.settings/org.eclipse.pde.prefs
  de.dlr.sc.virsat.fdir.storm.test/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.fdir.target/virsat_fdir_development.target
  de.dlr.sc.virsat.fdir.target/virsat_fdir_integration.target
  de.dlr.sc.virsat.model.extension.fdir.experiments/.settings/org.eclipse.pde.prefs
  de.dlr.sc.virsat.model.extension.fdir.experiments/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.model.extension.fdir.test/.settings/org.eclipse.pde.prefs
  de.dlr.sc.virsat.model.extension.fdir.test/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.model.extension.fdir.ui/.settings/org.eclipse.pde.prefs
  de.dlr.sc.virsat.model.extension.fdir.ui/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.model.extension.fdir/.settings/org.eclipse.pde.prefs
  de.dlr.sc.virsat.model.extension.fdir/META-INF/MANIFEST.MF
Labels: build

#145 Adjusted test structure - (Task #144)
  de.dlr.sc.virsat.fdir.test/pom.xml
  de.dlr.sc.virsat.fdir.test/src/de/dlr/sc/virsat/fdir/test/CoreAllTest.java
  de.dlr.sc.virsat.fdir.test/src/de/dlr/sc/virsat/fdir/test/ProjectAllTests.java
  launchers/VirSat FDIR All Tests.launch
Labels: build

#146 Improved build modularization - (Task #141)
  pom.xml
Labels: build

#149 Fixed exceptions - (Task #147)
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/snippet/UiSnippetTableCriticalityMatrixCriticalityMatrix.java
Labels: bug

#153 Using correct Activator - (Task #150)
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/model/FMECATest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/model/MCSAnalysisTest.java
  de.dlr.sc.virsat.model.extension.fdir.ui/resources/birt/savoir_fdir_report.rpttemplate
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/Activator.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/handler/CreateFdirReportHandler.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/snippet/UiSnippetTableMCSAnalysisMinimumCutSetsCutSet.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/Activator.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/CutSet.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/FMECA.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/FMECAEntry.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/MCSAnalysis.java
Labels: bug

#154 Added criticality matrix to the report template - (Task #151)
  de.dlr.sc.virsat.model.extension.fdir.ui/resources/birt/savoir_fdir_report.rpttemplate
Labels: feature

#155 Added highlighting rules to report template - (Task #152)
  de.dlr.sc.virsat.model.extension.fdir.ui/resources/birt/savoir_fdir_report.rpttemplate
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/FMECAEntry.java
Labels: feature

#158 Limited maximum number of shown chart entries - (Task #157)
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/snippet/UiSnippetTableAvailabilityAnalysisAvailabilityCurve.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/snippet/UiSnippetTableDetectabilityAnalysisDetectabilityCurve.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/snippet/UiSnippetTableReliabilityAnalysisReliabilityCurve.java
Labels: ui

#162 Fixed starting configuration - (Task #161)
  de.dlr.sc.virsat.fdir.product/virsat_fdir.product
Labels: bug
