Repository virtualsatellite/VirtualSatellite4-FDIR, pull requests merged in 2019-11, with the labels that each got.

#168 First implementation for schedule extraction - (Task #96)
  de.dlr.sc.virsat.fdir.storm.test/src/de/dlr/sc/virsat/fdir/storm/files/ExplicitPropFileWriterTest.java
  de.dlr.sc.virsat.fdir.storm.test/src/de/dlr/sc/virsat/fdir/storm/runner/StormDFTTest.java
  de.dlr.sc.virsat.fdir.storm.test/src/de/dlr/sc/virsat/fdir/storm/runner/StormRunnerFactoryTest.java
  de.dlr.sc.virsat.fdir.storm.test/src/de/dlr/sc/virsat/fdir/storm/runner/StormRunnerTest.java
  de.dlr.sc.virsat.fdir.storm.test/src/de/dlr/sc/virsat/fdir/storm/runner/StormSchedulerTest.java
  de.dlr.sc.virsat.fdir.storm.test/src/de/dlr/sc/virsat/fdir/storm/runner/StormTest.java
  de.dlr.sc.virsat.fdir.storm.test/src/de/dlr/sc/virsat/fdir/storm/test/AllTests.java
  de.dlr.sc.virsat.fdir.storm/.classpath
  de.dlr.sc.virsat.fdir.storm/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.fdir.storm/src/de/dlr/sc/virsat/fdir/storm/docker/DockerHelper.java
  de.dlr.sc.virsat.fdir.storm/src/de/dlr/sc/virsat/fdir/storm/files/ExplicitDRNFileWriter.java
  de.dlr.sc.virsat.fdir.storm/src/de/dlr/sc/virsat/fdir/storm/files/ExplicitPropertiesWriter.java
  de.dlr.sc.virsat.fdir.storm/src/de/dlr/sc/virsat/fdir/storm/files/IFileProvider.java
  de.dlr.sc.virsat.fdir.storm/src/de/dlr/sc/virsat/fdir/storm/runner/IStormProgram.java
  de.dlr.sc.virsat.fdir.storm/src/de/dlr/sc/virsat/fdir/storm/runner/Storm.java
  de.dlr.sc.virsat.fdir.storm/src/de/dlr/sc/virsat/fdir/storm/runner/StormDFT.java
  de.dlr.sc.virsat.fdir.storm/src/de/dlr/sc/virsat/fdir/storm/runner/StormRunner.java
  de.dlr.sc.virsat.fdir.storm/src/de/dlr/sc/virsat/fdir/storm/runner/StormScheduler.java
Labels: feature

#180 Feature/task 179 refactor preparation
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/markov/modelchecker/MarkovModelChecker.java
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/matrix/IMatrix.java
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/matrix/Matrix.java
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/matrix/MatrixFactory.java
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/matrix/MatrixIterator.java
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/matrix/TransitionMatrix.java
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/matrix/TransitionMatrixIterator.java
Labels: quality

#181 Renamed OBSERVER gate to MONITOR gate - (Task #166)
  de.dlr.sc.virsat.model.extension.fdir.experiments/resources/results/ftscs/mcs/composedRules.dot
  de.dlr.sc.virsat.model.extension.fdir.experiments/resources/results/ftscs/mcs/finalStateRule.dot
  de.dlr.sc.virsat.model.extension.fdir.experiments/resources/results/ftscs/mcs/original.dot
  de.dlr.sc.virsat.model.extension.fdir.experiments/resources/results/ftscs/mcs/orthogonalRule.dot
  de.dlr.sc.virsat.model.extension.fdir.experiments/resources/results/ftscs/mcs/traceEquivalenceRule.dot
  de.dlr.sc.virsat.model.extension.fdir.experiments/resources/results/ftscs/memory2WithNBackups/10_backups.dot
  de.dlr.sc.virsat.model.extension.fdir.experiments/resources/results/ftscs/memory2WithNBackups/11_backups.dot
  de.dlr.sc.virsat.model.extension.fdir.experiments/resources/results/ftscs/memory2WithNBackups/12_backups.dot
  de.dlr.sc.virsat.model.extension.fdir.experiments/resources/results/ftscs/memory2WithNBackups/13_backups.dot
  de.dlr.sc.virsat.model.extension.fdir.experiments/resources/results/ftscs/memory2WithNBackups/1_backups.dot
  de.dlr.sc.virsat.model.extension.fdir.experiments/resources/results/ftscs/memory2WithNBackups/2_backups.dot
  de.dlr.sc.virsat.model.extension.fdir.experiments/resources/results/ftscs/memory2WithNBackups/3_backups.dot
  de.dlr.sc.virsat.model.extension.fdir.experiments/resources/results/ftscs/memory2WithNBackups/4_backups.dot
  de.dlr.sc.virsat.model.extension.fdir.experiments/resources/results/ftscs/memory2WithNBackups/5_backups.dot
  de.dlr.sc.virsat.model.extension.fdir.experiments/resources/results/ftscs/memory2WithNBackups/6_backups.dot
  de.dlr.sc.virsat.model.extension.fdir.experiments/resources/results/ftscs/memory2WithNBackups/7_backups.dot
  de.dlr.sc.virsat.model.extension.fdir.experiments/resources/results/ftscs/memory2WithNBackups/8_backups.dot
  de.dlr.sc.virsat.model.extension.fdir.experiments/resources/results/ftscs/memory2WithNBackups/9_backups.dot
  de.dlr.sc.virsat.model.extension.fdir.experiments/src/de/dlr/sc/virsat/model/extension/fdir/experiments/ASynthesizerExperiment.java
  de.dlr.sc.virsat.model.extension.fdir.experiments/src/de/dlr/sc/virsat/model/extension/fdir/experiments/ftscs/FTSCS2018Experiments.java
  de.dlr.sc.virsat.model.extension.fdir.test/src-gen/de/dlr/sc/virsat/model/extension/fdir/model/AMONITORTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src-gen/de/dlr/sc/virsat/model/extension/fdir/test/AllTestsGen.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/model/MONITORTest.java
  de.dlr.sc.virsat.model.extension.fdir.ui/plugin.xml
  de.dlr.sc.virsat.model.extension.fdir.ui/resources/icons/MONITOR.gif
  de.dlr.sc.virsat.model.extension.fdir.ui/resources/icons/MONITOR_disabled.gif
  de.dlr.sc.virsat.model.extension.fdir.ui/src-gen/de/dlr/sc/virsat/model/extension/fdir/ui/PluginXml.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src-gen/de/dlr/sc/virsat/model/extension/fdir/ui/command/ACreateAddMONITORCommand.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src-gen/de/dlr/sc/virsat/model/extension/fdir/ui/handler/AAddMONITORHandler.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src-gen/de/dlr/sc/virsat/model/extension/fdir/ui/snippet/AUiSnippetSectionMONITOR.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src-gen/de/dlr/sc/virsat/model/extension/fdir/ui/snippet/AUiSnippetTableFaultTreeGatesMONITOR.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src-gen/de/dlr/sc/virsat/model/extension/fdir/ui/snippet/AUiSnippetTableMONITOR.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/command/CreateAddMONITORCommand.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/ft/FaultTreeDiagramImageProvider.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/ft/FaultTreeLayoutConnector.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/ft/features/faultTreeNodes/FaultTreeNodeAddFeature.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/ft/features/faultTreeNodes/FaultTreeNodeGraphicsFactory.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/ft/features/faultTreeNodes/FaultTreeNodeLayoutFeature.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/ft/features/faultTreeNodes/FaultTreeNodeUpdateFeature.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/handler/AddMONITORHandler.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/snippet/UiSnippetSectionMONITOR.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/snippet/UiSnippetTableFaultTreeGatesMONITOR.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/snippet/UiSnippetTableMONITOR.java
  de.dlr.sc.virsat.model.extension.fdir/concept/concept.concept
  de.dlr.sc.virsat.model.extension.fdir/concept/concept.xmi
  de.dlr.sc.virsat.model.extension.fdir/concept/concept_v1_1.xmi
  de.dlr.sc.virsat.model.extension.fdir/plugin.xml
  de.dlr.sc.virsat.model.extension.fdir/src-gen/de/dlr/sc/virsat/model/extension/fdir/model/AMONITOR.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/DFT2GalileoDFT.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/GalileoDFT2DFT.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2dft/DFT2BasicDFTConverter.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/DFTState.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/po/ObservationEvent.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/po/PONDDFTSemantics.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/semantics/DFTSemantics.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/FaultTreeNodeType.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/MONITOR.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/util/FaultTreeHelper.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/util/FaultTreeHolder.java
Labels: quality

#182 Updated project natures to maven projects - (Task #148)
  .project
  de.dlr.sc.virsat.fdir.branding.feature/.project
  de.dlr.sc.virsat.fdir.branding.ui/.project
  de.dlr.sc.virsat.fdir.core.test/.project
  de.dlr.sc.virsat.fdir.core/.project
  de.dlr.sc.virsat.fdir.docs.feature/.project
  de.dlr.sc.virsat.fdir.galileo.feature/.project
  de.dlr.sc.virsat.fdir.galileo.ide/.project
  de.dlr.sc.virsat.fdir.galileo.tests/.project
  de.dlr.sc.virsat.fdir.galileo.ui/.project
  de.dlr.sc.virsat.fdir.galileo/.project
  de.dlr.sc.virsat.fdir.license.feature/.project
  de.dlr.sc.virsat.fdir.p2updatesite/.project
  de.dlr.sc.virsat.fdir.product/.project
  de.dlr.sc.virsat.fdir.storm.test/.project
  de.dlr.sc.virsat.fdir.storm/.project
  de.dlr.sc.virsat.fdir.storm/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.fdir.target/.project
  de.dlr.sc.virsat.fdir.test.feature/.project
  de.dlr.sc.virsat.fdir.test/.project
  de.dlr.sc.virsat.model.extension.fdir.experiments/.project
  de.dlr.sc.virsat.model.extension.fdir.feature/.project
  de.dlr.sc.virsat.model.extension.fdir.test/.project
  de.dlr.sc.virsat.model.extension.fdir.ui/.project
  de.dlr.sc.virsat.model.extension.fdir/.project
Labels: build, quality

#186 Improved monitoring of FMECA Analysis - (Task #184)
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/AvailabilityAnalysis.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/FMECA.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/ReliabilityAnalysis.java
Labels: quality, ui

#185 Added missing check for canExecute in command - (Task #183)
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/command/CreateDeleteWithReferencingFDIRCategoryAssignmentsCommand.java
Labels: bug

#188 Improved crosslinking nodes in different trees - (Task #187)
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/model/FaultTreeTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/modularizer/ModularizerTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/util/FaultTreeHolderTest.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2dft/DFT2BasicDFTConverter.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/FMECA.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/Fault.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/FaultTree.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/util/FaultTreeHelper.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/util/FaultTreeHolder.java
Labels: bug

#192 Setting flag to use UUIDs - (Task #191)
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/wizards/ExportGalileoDFTWizard.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/DFT2GalileoDFT.java
Labels: bug
