Repository virtualsatellite/VirtualSatellite4-FDIR, pull requests merged in 2019-12, with the labels that each got.

#196 Updated checkstyle version - (Task #189)
  checkStyleSuppression.xml
  checkStylesDefinition.xml
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/matrix/Matrix.java
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/metrics/IQuantitativeMetric.java
  de.dlr.sc.virsat.fdir.storm/src/de/dlr/sc/virsat/fdir/storm/files/ExplicitPropertiesWriter.java
  de.dlr.sc.virsat.fdir.storm/src/de/dlr/sc/virsat/fdir/storm/runner/StormDFT.java
  de.dlr.sc.virsat.fdir.storm/src/de/dlr/sc/virsat/fdir/storm/runner/StormModelChecker.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/migrator/Migrator1v0Test.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/migrator/Migrator1v1Test.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/synthesizer/POSynthesizerTest.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/migrator/Migrator1v0.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/migrator/Migrator1v1.java
  maven/pom.xml
Labels: build

#198 Updated concept files - (Task #197)
  de.dlr.sc.virsat.model.extension.fdir/concept/concept.concept
  de.dlr.sc.virsat.model.extension.fdir/concept/concept.xmi
  de.dlr.sc.virsat.model.extension.fdir/concept/concept_v1_1.xmi
Labels: feature

#199 Feature/task 195 create validator for
  de.dlr.sc.virsat.model.extension.fdir.test/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.model.extension.fdir.test/src-gen/de/dlr/sc/virsat/model/extension/fdir/test/AllTestsGen.java
  de.dlr.sc.virsat.model.extension.fdir.test/src-gen/de/dlr/sc/virsat/model/extension/fdir/validator/AStructuralElementInstanceValidatorTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/test/AllTests.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/validator/FaultValidatorTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/validator/StructuralElementInstanceValidatorTest.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/FaultTreeEdge.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/util/FaultTreeHelper.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/validator/FaultValidator.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/validator/StructuralElementInstanceValidator.java
Labels: feature

#201 Updated concept - (Task #200)
  de.dlr.sc.virsat.model.extension.fdir/concept/concept.concept
  de.dlr.sc.virsat.model.extension.fdir/concept/concept.xmi
  de.dlr.sc.virsat.model.extension.fdir/concept/concept_v1_1.xmi
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/util/FaultTreeHolder.java
Labels: ui

#203 Set icon for wizards - (Task #202)
  de.dlr.sc.virsat.fdir.target/tmodel-src/virsat_fdir_development.tmodel
  de.dlr.sc.virsat.fdir.target/virsat_fdir_development.target
  de.dlr.sc.virsat.model.extension.fdir.ui/plugin.xml
Labels: ui

#204 Replaced type label with editable name label - (Task #130)
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/ft/FaultTreeFeatureProvider.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/ft/features/faultTreeNodes/FaultTreeNodeAddFeature.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/ft/features/faultTreeNodes/FaultTreeNodeGraphicsFactory.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/ft/features/faultTreeNodes/FaultTreeNodeLayoutFeature.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/ft/features/faultTreeNodes/FaultTreeNodeUpdateFeature.java
Labels: ui

#207 Feature/task 206 improve mcsa monitori
  de.dlr.sc.virsat.model.extension.fdir.experiments/src/de/dlr/sc/virsat/model/extension/fdir/experiments/aiaa/AIAA2017Experiments.java
  de.dlr.sc.virsat.model.extension.fdir.experiments/src/de/dlr/sc/virsat/model/extension/fdir/experiments/aiaa/AIAA2018Experiments.java
  de.dlr.sc.virsat.model.extension.fdir.experiments/src/de/dlr/sc/virsat/model/extension/fdir/experiments/ftscs/FTSCS2018Experiments.java
  de.dlr.sc.virsat.model.extension.fdir.experiments/src/de/dlr/sc/virsat/model/extension/fdir/experiments/ftscs/SCP2019Experiments.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/FaultTreeEvaluator.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/AvailabilityAnalysis.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/DetectabilityAnalysis.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/FMECA.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/MCSAnalysis.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/ReliabilityAnalysis.java
Labels: quality

#208 Disabled symmetry reduction for reduced failables - (Task #205)
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/semantics/DFTSemantics.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/DFTEvaluator.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/util/FaultTreeHelper.java
Labels: bug

#209 Feature/sps
  de.dlr.sc.virsat.fdir.core.test/src/de/dlr/sc/virsat/fdir/core/markov/modelchecker/MarkovModelCheckerTest.java
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/markov/modelchecker/MarkovModelChecker.java
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/matrix/IMatrix.java
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/matrix/Matrix.java
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/matrix/MatrixFactory.java
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/matrix/MatrixIterator.java
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/matrix/SPSIterator.java
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/matrix/TransitionMatrix.java
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/matrix/TransitionMatrixIterator.java
Labels: feature, quality

#214 Integration 4.10.0 - Remerge Versions
  build.xml
  de.dlr.sc.virsat.fdir.branding.feature/feature.xml
  de.dlr.sc.virsat.fdir.branding.feature/pom.xml
  de.dlr.sc.virsat.fdir.branding.ui/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.fdir.branding.ui/plugin.xml
  de.dlr.sc.virsat.fdir.branding.ui/pom.xml
  de.dlr.sc.virsat.fdir.core.test/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.fdir.core.test/pom.xml
  de.dlr.sc.virsat.fdir.core/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.fdir.core/pom.xml
  de.dlr.sc.virsat.fdir.docs.feature/docs/VirSat_FDIR_ReleaseNotes.txt
  de.dlr.sc.virsat.fdir.docs.feature/feature.xml
  de.dlr.sc.virsat.fdir.docs.feature/pom.xml
  de.dlr.sc.virsat.fdir.galileo.feature/feature.xml
  de.dlr.sc.virsat.fdir.galileo.feature/pom.xml
  de.dlr.sc.virsat.fdir.galileo.ide/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.fdir.galileo.ide/pom.xml
  de.dlr.sc.virsat.fdir.galileo.tests/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.fdir.galileo.tests/pom.xml
  de.dlr.sc.virsat.fdir.galileo.ui/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.fdir.galileo.ui/pom.xml
  de.dlr.sc.virsat.fdir.galileo/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.fdir.galileo/pom.xml
  de.dlr.sc.virsat.fdir.license.feature/feature.xml
  de.dlr.sc.virsat.fdir.license.feature/pom.xml
  de.dlr.sc.virsat.fdir.p2updatesite/category.xml
  de.dlr.sc.virsat.fdir.p2updatesite/pom.xml
  de.dlr.sc.virsat.fdir.product/pom.xml
  de.dlr.sc.virsat.fdir.product/virsat_fdir.product
  de.dlr.sc.virsat.fdir.storm.test/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.fdir.storm.test/pom.xml
  de.dlr.sc.virsat.fdir.storm/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.fdir.storm/pom.xml
  de.dlr.sc.virsat.fdir.target/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.fdir.target/pom.xml
  de.dlr.sc.virsat.fdir.target/tmodel-src/virsat_fdir_integration.tmodel
  de.dlr.sc.virsat.fdir.target/tmodel-src/virsat_fdir_release.tmodel
  de.dlr.sc.virsat.fdir.target/virsat_fdir_development.target
  de.dlr.sc.virsat.fdir.target/virsat_fdir_integration.target
  de.dlr.sc.virsat.fdir.target/virsat_fdir_release.target
  de.dlr.sc.virsat.fdir.test.feature/feature.xml
  de.dlr.sc.virsat.fdir.test.feature/pom.xml
  de.dlr.sc.virsat.fdir.test/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.fdir.test/pom.xml
  de.dlr.sc.virsat.model.extension.fdir.feature/feature.xml
  de.dlr.sc.virsat.model.extension.fdir.feature/pom.xml
  de.dlr.sc.virsat.model.extension.fdir.test/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.model.extension.fdir.test/pom.xml
  de.dlr.sc.virsat.model.extension.fdir.ui/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.model.extension.fdir.ui/pom.xml
  de.dlr.sc.virsat.model.extension.fdir/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.model.extension.fdir/pom.xml
  maven/pom.xml
  pom.xml
Labels: release
