Repository virtualsatellite/VirtualSatellite4-FDIR, pull requests merged in 2019-07, with the labels that each got.

#6 Release 4.9.0 - Release #2
  maven/pom.xml
Labels: release

#5 Integration 4.9.0 - Remerge
  .github/ISSUE_TEMPLATE/Release.md
  .travis.yml
  de.dlr.sc.virsat.fdir.docs.feature/docs/VirSat_FDIR_ReleaseNotes.txt
  de.dlr.sc.virsat.fdir.galileo/xtend-gen/de/dlr/sc/virsat/fdir/galileo/.gitignore
  de.dlr.sc.virsat.fdir.p2updatesite/pom.xml
  de.dlr.sc.virsat.fdir.target/tmodel-src/virsat_fdir_integration.tmodel
  de.dlr.sc.virsat.fdir.target/virsat_fdir_integration.target
  launchers/VirSat FDIR Build Integration (Deploy).launch
  maven/pom.xml
  settings.xml
Labels: release

#10 Feature/task 7 implement modularizatio
  de.dlr.sc.virsat.fdir.galileo.ide/xtend-gen/de/dlr/sc/virsat/fdir/galileo/ide/.gitignore
  de.dlr.sc.virsat.fdir.galileo.tests/xtend-gen/de/dlr/sc/virsat/fdir/galileo/tests/.gitignore
  de.dlr.sc.virsat.fdir.galileo.ui/xtend-gen/de/dlr/sc/virsat/fdir/galileo/ui/.gitignore
  de.dlr.sc.virsat.fdir.galileo.ui/xtend-gen/de/dlr/sc/virsat/fdir/galileo/ui/contentassist/.gitignore
  de.dlr.sc.virsat.fdir.galileo.ui/xtend-gen/de/dlr/sc/virsat/fdir/galileo/ui/labeling/.gitignore
  de.dlr.sc.virsat.fdir.galileo.ui/xtend-gen/de/dlr/sc/virsat/fdir/galileo/ui/outline/.gitignore
  de.dlr.sc.virsat.fdir.galileo.ui/xtend-gen/de/dlr/sc/virsat/fdir/galileo/ui/quickfix/.gitignore
  de.dlr.sc.virsat.fdir.galileo/xtend-gen/de/dlr/sc/virsat/fdir/galileo/.gitignore
  de.dlr.sc.virsat.fdir.galileo/xtend-gen/de/dlr/sc/virsat/fdir/galileo/formatting/.gitignore
  de.dlr.sc.virsat.fdir.galileo/xtend-gen/de/dlr/sc/virsat/fdir/galileo/generator/.gitignore
  de.dlr.sc.virsat.fdir.galileo/xtend-gen/de/dlr/sc/virsat/fdir/galileo/scoping/.gitignore
  de.dlr.sc.virsat.fdir.galileo/xtend-gen/de/dlr/sc/virsat/fdir/galileo/validation/.gitignore
  de.dlr.sc.virsat.fdir.target/virsat_fdir_release.target
  de.dlr.sc.virsat.fdir.test/launch/VirSat FDIR All Tests.launch
  de.dlr.sc.virsat.model.extension.fdir.test/resources/galileo/fdep2.dft
  de.dlr.sc.virsat.model.extension.fdir.test/resources/galileo/fdep3Spare2.dft
  de.dlr.sc.virsat.model.extension.fdir.test/resources/galileo/nestedPand.dft
  de.dlr.sc.virsat.model.extension.fdir.test/resources/galileo/nestedPand2.dft
  de.dlr.sc.virsat.model.extension.fdir.test/resources/galileo/or2And2Basic.dft
  de.dlr.sc.virsat.model.extension.fdir.test/resources/galileo/or2And2SharedSpare.dft
  de.dlr.sc.virsat.model.extension.fdir.test/resources/galileo/or3AndColdSpareBasic.dft
  de.dlr.sc.virsat.model.extension.fdir.test/resources/galileo/or3Pand2ColdSpare.dft
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/modularizer/ModularizerTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/test/AllTests.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/modularizer/FaultTreeNodePlus.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/modularizer/IModularizer.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/modularizer/Modularizer.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/modularizer/Module.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/modularizer/ModuleType.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/util/FaultTreeHelper.java
Labels: feature

#14 Added additional obervability condition - (Task #13)
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/explicit/po/PONDDFTSemantics.java
Labels: feature

#11 Feature/task 8 implement parallel comp
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/recovery/ParallelComposerTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/test/AllTests.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/recovery/ParallelComposer.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/util/RecoveryAutomatonHelper.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/util/RecoveryAutomatonHolder.java
Labels: feature

#26 Added test case for schedule 2 ra converter - (Task #25)
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/synthesizer/Schedule2RAConverterTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/test/AllTests.java
Labels: quality

#27 Feature/task 24 partial observable sch
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/markov/MarkovTransition.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/synthesizer/POSynthesizerTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/synthesizer/Schedule2RAConverterTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/test/AllTests.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/explicit/DFTSemantics.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/synthesizer/ASynthesizer.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/synthesizer/POSynthesizer.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/synthesizer/Schedule2RAConverter.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/util/RecoveryAutomatonHelper.java
Labels: feature

#30 Added test case generating timed transitions - (Task #28)
  de.dlr.sc.virsat.model.extension.fdir.test/resources/galileoObs/obsMemory2RDEP.dft
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/synthesizer/POSynthesizerTest.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/recovery/minimizer/OrthogonalPartitionRefinementMinimizer.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/synthesizer/ASynthesizer.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/synthesizer/POSynthesizer.java
Labels: quality

#35 Calling the delegate synthesizer in UI - (Task #31)
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/synthesizer/DelegateSynthesizerTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/synthesizer/POSynthesizerTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/test/AllTests.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/snippet/custom/UiSnippetFdirGenerator.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/synthesizer/ASynthesizer.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/synthesizer/DelegateSynthesizer.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/synthesizer/ISynthesizer.java
Labels: quality

#36 Refactored result passing in model checking - (Task #34)
  de.dlr.sc.virsat.fdir.core.test/src/de/dlr/sc/virsat/fdir/core/markov/modelchecker/MarkovModelCheckerTest.java
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/markov/modelchecker/IMarkovModelChecker.java
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/markov/modelchecker/MarkovModelChecker.java
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/markov/modelchecker/ModelCheckingResult.java
  de.dlr.sc.virsat.fdir.storm.test/src/de/dlr/sc/virsat/fdir/storm/runner/StormModelCheckerTest.java
  de.dlr.sc.virsat.fdir.storm/src/de/dlr/sc/virsat/fdir/storm/runner/StormModelChecker.java
  de.dlr.sc.virsat.model.extension.fdir.experiments/src/de/dlr/sc/virsat/model/extension/fdir/experiments/ASynthesizerExperiment.java
  de.dlr.sc.virsat.model.extension.fdir.experiments/src/de/dlr/sc/virsat/model/extension/fdir/experiments/aiaa/AIAA2017Experiments.java
  de.dlr.sc.virsat.model.extension.fdir.experiments/src/de/dlr/sc/virsat/model/extension/fdir/experiments/aiaa/AIAA2018Experiments.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2dft/DFT2BasicDFTConverterTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/ADFT2MAConverterTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/explicit/ExplicitDFT2MAConverterTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/explicit/po/PONDDFTSemanticsTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/StormEvaluatorTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/synthesizer/BasicSynthesizerTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/test/ATestCase.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/DFTEvaluator.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/FMECAEvaluator.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/FaultTreeEvaluator.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/IFaultTreeEvaluator.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/StormEvaluator.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/AvailabilityAnalysis.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/ReliabilityAnalysis.java
Labels: quality

#40 Refactoring to allow for po semantics in workflow - (Task #32)
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/DFT2MAConverterTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/po/PONDDFTSemanticsTest.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/DFTEvaluator.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/FaultTreeEvaluator.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/synthesizer/DelegateSynthesizer.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/util/FaultTreeHolder.java
Labels: feature

#41 Displaying the observation rate - (Task #17)
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/ft/features/faultTreeNodes/FaultTreeNodeAddFeature.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/ft/features/faultTreeNodes/FaultTreeNodeLayoutFeature.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/ft/features/faultTreeNodes/FaultTreeNodeUpdateFeature.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/GalileoDFT2DFT.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2dft/DFT2BasicDFTConverter.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/DFTState.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/util/FaultTreeHolder.java
  launchers/VirSat FDIR Application.launch
Labels: feature, ui

#45 Feature/task 44 refactor and test op cl
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/calculation/OpClassifyPLTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/test/AllTests.java
  de.dlr.sc.virsat.model.extension.fdir/concept/concept.concept
  de.dlr.sc.virsat.model.extension.fdir/concept/concept.xmi
  de.dlr.sc.virsat.model.extension.fdir/concept/concept_v1_1.xmi
  de.dlr.sc.virsat.model.extension.fdir/plugin.xml
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/calculation/OpClassify.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/calculation/OpClassifyPL.java
Labels: quality

#48 Feature/task 20 move classification ma
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/calculation/FDIRExpressionEvaluatorTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/calculation/FDIRExpressionExtensionTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/calculation/FDIRParametersGetterTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/calculation/OpClassifyPLTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/model/FDIRParametersTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/model/FMECATest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/test/AllTests.java
  de.dlr.sc.virsat.model.extension.fdir.ui/plugin.xml
  de.dlr.sc.virsat.model.extension.fdir.ui/src-gen/de/dlr/sc/virsat/model/extension/fdir/ui/snippet/AUiSnippetTableFDIRParametersProbabilityLevels.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/command/CreateAddFDIRParametersCommand.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/snippet/UiSnippetTableFDIRParametersProbabilityLevels.java
  de.dlr.sc.virsat.model.extension.fdir/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.model.extension.fdir/concept/concept.concept
  de.dlr.sc.virsat.model.extension.fdir/concept/concept.xmi
  de.dlr.sc.virsat.model.extension.fdir/concept/concept_v1_1.xmi
  de.dlr.sc.virsat.model.extension.fdir/plugin.xml
  de.dlr.sc.virsat.model.extension.fdir/src-gen/de/dlr/sc/virsat/model/extension/fdir/model/AFDIRParameters.java
  de.dlr.sc.virsat.model.extension.fdir/src-gen/de/dlr/sc/virsat/model/extension/fdir/model/AFMECAEntry.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/calculation/ArrayResult.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/calculation/FDIRExpressionEvaluator.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/calculation/FDIRExpressionExtension.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/calculation/FDIRParametersGetter.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/calculation/OpClassifyPL.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/FDIRParameters.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/FMECA.java
Labels: feature, ui

#52 Feature/task 51 refactor analysis code
  de.dlr.sc.virsat.fdir.core.test/src/de/dlr/sc/virsat/fdir/core/markov/modelchecker/MarkovModelCheckerTest.java
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/markov/modelchecker/MarkovModelChecker.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/snippet/UiSnippetSectionAvailabilityAnalysis.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/snippet/UiSnippetSectionReliabilityAnalysis.java
  de.dlr.sc.virsat.model.extension.fdir/concept/concept.concept
  de.dlr.sc.virsat.model.extension.fdir/concept/concept.xmi
  de.dlr.sc.virsat.model.extension.fdir/concept/concept_v1_1.xmi
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/AvailabilityAnalysis.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/FMECA.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/ReliabilityAnalysis.java
Labels: quality

#55 Implemented helper method - (Task #54)
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/po/PONDDFTSemanticsTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/test/AllTests.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/util/FaultTreeHolderTest.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/util/FaultTreeHolder.java
Labels: quality

#46 Feature/task 21 improve trimming logic and copy fault trees
  de.dlr.sc.virsat.model.extension.fdir.test/resources/galileo/nestedPand.dft
  de.dlr.sc.virsat.model.extension.fdir.test/resources/galileo/nestedPand2.dft
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/modularizer/ModularizerTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/modularizer/ModuleTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/recovery/ParallelComposerTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/synthesizer/BasicSynthesizerTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/test/AllTests.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/trimmer/FaultTreeTrimmerTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/util/FaultTreeHelperTest.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/modularizer/FaultTreeNodePlus.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/modularizer/Modularizer.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/modularizer/Module.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/modularizer/ModuleType.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/recovery/ParallelComposer.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/synthesizer/ASynthesizer.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/synthesizer/ISynthesizer.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/trimmer/FaultTreeTrimmer.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/util/FaultTreeHelper.java
Labels: feature, quality

#71 updated target platform - (Task #66)
  de.dlr.sc.virsat.fdir.target/virsat_fdir_development.target
Labels: build

#69 Enabled project for external contributions
  .mailmap
  .travis.yml
  README.md
  bash/verify_commit_authors.sh
  known_authors.txt
Labels: build

#65 Feature/task 62 refactor test setup to
  de.dlr.sc.virsat.model.extension.fdir.experiments/src/de/dlr/sc/virsat/model/extension/fdir/experiments/ASynthesizerExperiment.java
  de.dlr.sc.virsat.model.extension.fdir.experiments/src/de/dlr/sc/virsat/model/extension/fdir/experiments/aiaa/AIAA2017Experiments.java
  de.dlr.sc.virsat.model.extension.fdir.experiments/src/de/dlr/sc/virsat/model/extension/fdir/experiments/aiaa/AIAA2018Experiments.java
  de.dlr.sc.virsat.model.extension.fdir.experiments/src/de/dlr/sc/virsat/model/extension/fdir/experiments/ftscs/FTSCS2018Experiments.java
  de.dlr.sc.virsat.model.extension.fdir.experiments/src/de/dlr/sc/virsat/model/extension/fdir/experiments/ftscs/SCP2019Experiments.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/converter/DFT2GalileoDFTTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2dft/DFT2BasicDFTConverterTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/DFT2MAConverterTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/StormEvaluatorTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/modularizer/ModularizerTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/modularizer/ModuleTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/recovery/ParallelComposerTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/recovery/minimizer/AMinimizerTestCase.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/recovery/minimizer/CleanMinimizerTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/recovery/minimizer/ComposedMinimizerTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/recovery/minimizer/FinalStateMinimizerTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/recovery/minimizer/OrthogonalPartitionRefinementMinimizerTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/recovery/minimizer/PartitionRefinementMinimizerTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/synthesizer/BasicSynthesizerTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/test/ATestCase.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/trimmer/FaultTreeTrimmerTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/util/FaultTreeHelperTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/util/RecoveryAutomatonHelperTest.java
Labels: quality

#73 Adding students - (Task #72)
  .mailmap
  known_authors.txt
Labels: build

#75 Trying out new build scripts - (Task #70)
  .travis.yml
  bash/deploy_sourceforge.sh
  bash/maven_build.sh
Labels: build

#77 Feature/task 76 fix performance bug in
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/DFT2MAConverterTest.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/FaultEvent.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/semantics/DFTSemantics.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/ClaimAction.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/RecoveryAction.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/recovery/RecoveryStrategy.java
Labels: bug

#79 Feature/task 74 copy module fault tree
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/modularizer/ModuleTest.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/modularizer/Module.java
Labels: feature, quality

#81 Feature/task 78 improve run times
  de.dlr.sc.virsat.model.extension.fdir.test/resources/galileo/sharedSpareWithSideNode.dft
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/modularizer/ModuleTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/synthesizer/BasicSynthesizerTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/trimmer/FaultTreeTrimmerTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/util/FaultTreeHelperTest.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/modularizer/Modularizer.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/modularizer/Module.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/recovery/ParallelComposer.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/recovery/minimizer/ComposedMinimizer.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/synthesizer/ASynthesizer.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/trimmer/FaultTreeTrimmer.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/util/FaultTreeHelper.java
Labels: feature, quality
