Repository virtualsatellite/VirtualSatellite4-FDIR, pull requests merged in 2019-10, with the labels that each got.

#165 Fixed bug in diagram editor - (Task #164)
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/ft/FaultTreeDiagramToolBehaviorProvider.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/snippet/UiSnippetTableReliabilityAnalysisReliabilityCurve.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/DFTState.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/semantics/DFTSemantics.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/util/FaultTreeHolder.java
Labels: bug, ui

#167 Added stripping of whitelines - (Task #166)
  bash/verify_commit_authors.sh
  known_authors.txt
Labels: bug, build

#171 Renamed property to "compensation" - (Task #159)
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/model/FMECATest.java
  de.dlr.sc.virsat.model.extension.fdir.ui/plugin.xml
  de.dlr.sc.virsat.model.extension.fdir.ui/src-gen/de/dlr/sc/virsat/model/extension/fdir/ui/command/ACreateAddArrayElementCompensationCommand.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src-gen/de/dlr/sc/virsat/model/extension/fdir/ui/snippet/AUiSnippetTableFMECAEntryCompensation.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/command/CreateAddArrayElementCompensationCommand.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/snippet/UiSnippetTableFMECAEntryCompensation.java
  de.dlr.sc.virsat.model.extension.fdir/concept/concept.concept
  de.dlr.sc.virsat.model.extension.fdir/concept/concept.xmi
  de.dlr.sc.virsat.model.extension.fdir/concept/concept_v1_1.xmi
  de.dlr.sc.virsat.model.extension.fdir/src-gen/de/dlr/sc/virsat/model/extension/fdir/model/AFMECAEntry.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/FMECAEntry.java
Labels: ui

#175 Delayed cascade deletion - (Task #57)
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/command/CreateDeleteWithReferencingFDIRCategoryAssignmentsCommand.java
Labels: bug

#172 Feature/task 59 hand over progress mon
  de.dlr.sc.virsat.fdir.core.test/src/de/dlr/sc/virsat/fdir/core/markov/modelchecker/MarkovModelCheckerTest.java
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/markov/modelchecker/IMarkovModelChecker.java
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/markov/modelchecker/MarkovModelChecker.java
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/metrics/Availability.java
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/metrics/IBaseMetric.java
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/metrics/IBaseMetricVisitor.java
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/metrics/MTTF.java
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/metrics/MinimumCutSet.java
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/metrics/Reliability.java
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/metrics/SteadyStateAvailability.java
  de.dlr.sc.virsat.fdir.storm.test/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.fdir.storm.test/src/de/dlr/sc/virsat/fdir/storm/runner/StormModelCheckerTest.java
  de.dlr.sc.virsat.fdir.storm/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.fdir.storm/src/de/dlr/sc/virsat/fdir/storm/files/ExplicitPropertiesWriter.java
  de.dlr.sc.virsat.fdir.storm/src/de/dlr/sc/virsat/fdir/storm/runner/StormDFT.java
  de.dlr.sc.virsat.fdir.storm/src/de/dlr/sc/virsat/fdir/storm/runner/StormModelChecker.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/DFTMetricsComposerTest.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/DFTEvaluator.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/DFTMetricsComposer.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/FaultTreeEvaluator.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/IFaultTreeEvaluator.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/StormDFTEvaluator.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/MCSAnalysis.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/ReliabilityAnalysis.java
  known_authors.txt
Labels: ui

#177 Feature/task 176 interface changes for
  de.dlr.sc.virsat.fdir.core/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/markov/modelchecker/MarkovModelChecker.java
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/matrix/IMatrix.java
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/matrix/Matrix.java
Labels: feature
