Repository virtualsatellite/VirtualSatellite4-FDIR, pull requests merged in 2020-05, with the labels that each got.

#286 Wrote Fault Tree Diagram chapter in User manual - (Task #277)
  de.dlr.sc.virsat.fdir.docs.feature/docs/VirSat_FDIR_User_Manual.pdf
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/VirSat_FDIR_User_Manual.adoc
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/faultTrees/Comment.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/faultTrees/Comment_Diagram.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/faultTrees/Expand_Diagram.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/faultTrees/Galileo.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/faultTrees/Layout_Diagram.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/faultTrees/Layout_View_Diagram.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/faultTrees/diagramEditor.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/recoveryAutomata/ClaimAction.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/recoveryAutomata/FaultEventTransition.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/recoveryAutomata/FaultEventTransition_Diagram.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/recoveryAutomata/FreeAction.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/recoveryAutomata/State.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/recoveryAutomata/State_Diagram.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/recoveryAutomata/TimedTransition.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/recoveryAutomata/TimedTransition_Diagram.png
Labels: quality

#284 Graphiti Editor: Added drag and drop - (Task #283)
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/ft/AnchorUtil.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/ft/FaultTreeFeatureProvider.java
Labels: comfort/usability, feature, ui

#288 Updated recovery automaton section - (Task #287)
  de.dlr.sc.virsat.fdir.docs.feature/docs/VirSat_FDIR_User_Manual.pdf
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/VirSat_FDIR_User_Manual.adoc
Labels: documentation

#290 Feature/task 289 create chapter on fdi
  de.dlr.sc.virsat.fdir.docs.feature/docs/VirSat_FDIR_User_Manual.pdf
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/VirSat_FDIR_User_Manual.adoc
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/analysis/CriticalityMatrix_Table.png
Labels: documentation

#292 Feature/task 291 write manual chapter
  de.dlr.sc.virsat.fdir.docs.feature/docs/VirSat_FDIR_User_Manual.pdf
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/VirSat_FDIR_User_Manual.adoc
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/reports/AddReport.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/reports/ReportTarget.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/reports/ViewReport.png
Labels: documentation

#294 Created short chapter on using the fdir synthesis - (Task #293)
  de.dlr.sc.virsat.fdir.docs.feature/docs/VirSat_FDIR_User_Manual.pdf
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/VirSat_FDIR_User_Manual.adoc
Labels: documentation

#297 Bundled maps into logical units - (Task #296)
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/markov/modelchecker/MarkovModelChecker.java
  de.dlr.sc.virsat.fdir.storm/src/de/dlr/sc/virsat/fdir/storm/files/ExplicitDRNFileWriter.java
  de.dlr.sc.virsat.fdir.storm/src/de/dlr/sc/virsat/fdir/storm/files/ExplicitPropertiesWriter.java
  de.dlr.sc.virsat.fdir.storm/src/de/dlr/sc/virsat/fdir/storm/files/IExplicitFileWriter.java
  de.dlr.sc.virsat.fdir.storm/src/de/dlr/sc/virsat/fdir/storm/files/InstanceFileGenerator.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/FaultTreeSymmetryCheckerTest.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft/analysis/DFTStaticAnalysis.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft/analysis/DFTSymmetryChecker.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2dft/DFT2BasicDFTConverter.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/DFT2MAConverter.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/DFTState.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/events/FaultEvent.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/po/ObservationEvent.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/po/PODFTState.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/po/PONDDFTSemantics.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/semantics/DFTSemantics.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/semantics/DelaySemantics.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/semantics/FDEPSemantics.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/semantics/FaultSemantics.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/semantics/NDSPARESemantics.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/semantics/PORSemantics.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/semantics/StandardSPARESemantics.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/semantics/VOTESemantics.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/DFTMetricsComposer.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/ClaimAction.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/FreeAction.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/modularizer/Modularizer.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/util/BasicEventHolder.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/util/EdgeType.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/util/FaultTreeHolder.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/util/NodeHolder.java
Labels: quality

#300 Feature/task 298 improve test case ass
  de.dlr.sc.virsat.fdir.core.test/src/de/dlr/sc/virsat/fdir/core/markov/scheduler/MarkovSchedulerTest.java
  de.dlr.sc.virsat.fdir.core.test/src/de/dlr/sc/virsat/fdir/core/test/TestResourceGetter.java
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/markov/scheduler/MarkovAutomatonValueIterator.java
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/markov/scheduler/MarkovScheduler.java
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/matrix/BellmanMatrix.java
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/matrix/MatrixFactory.java
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/metrics/AProbabilityCurve.java
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/metrics/IMetric.java
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/metrics/MeanTimeToDetection.java
  de.dlr.sc.virsat.fdir.storm.test/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.fdir.storm.test/resources/writeTest.drn
  de.dlr.sc.virsat.fdir.storm.test/resources/writeTest.prop
  de.dlr.sc.virsat.fdir.storm.test/src/de/dlr/sc/virsat/fdir/storm/files/ExplicitDRNFileWriterTest.java
  de.dlr.sc.virsat.fdir.storm.test/src/de/dlr/sc/virsat/fdir/storm/files/ExplicitPropFileWriterTest.java
  de.dlr.sc.virsat.fdir.storm/src/de/dlr/sc/virsat/fdir/storm/files/ExplicitDRNFileWriter.java
  de.dlr.sc.virsat.fdir.storm/src/de/dlr/sc/virsat/fdir/storm/files/ExplicitPropertiesWriter.java
  de.dlr.sc.virsat.model.extension.fdir.experiments/src/de/dlr/sc/virsat/model/extension/fdir/experiments/aiaa/AIAA2017Experiments.java
  de.dlr.sc.virsat.model.extension.fdir.test/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/converter/GalileoDFT2DFTTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/DFTEvaluatorTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/synthesizer/BasicSynthesizerTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/synthesizer/POSynthesizerTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/test/ATestCase.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/test/TestActivator.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/calculation/FDIRExpressionEvaluator.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/DFTState.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/ma2beliefMa/BeliefState.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/DFTEvaluator.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/DFTMetricsComposer.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/DFTModularization.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/FaultTreeEvaluator.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/migrator/Migrator1v0.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/migrator/Migrator1v1.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/synthesizer/ASynthesizer.java
Labels: quality

#309 Feature/task 308 improve testing of or
  de.dlr.sc.virsat.fdir.core.test/src/de/dlr/sc/virsat/fdir/core/markov/MarkovTransitionTest.java
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/markov/MarkovAutomaton.java
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/markov/MarkovTransition.java
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/markov/modelchecker/MarkovModelChecker.java
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/markov/scheduler/MarkovScheduler.java
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/matrix/BellmanMatrix.java
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/matrix/MatrixFactory.java
  de.dlr.sc.virsat.model.extension.fdir.test/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/DFTEvaluatorTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/modularizer/FaultTreeTrimmerTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/recovery/minimizer/OrthogonalPartitionRefinementMinimizerTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/recovery/minimizer/PartitionRefinementMinimizerTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/synthesizer/BasicSynthesizerTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/synthesizer/POSynthesizerTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/test/AllTests.java
  de.dlr.sc.virsat.model.extension.fdir/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/DFTState.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/DFTStateEquivalence.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/po/PODFTState.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/ma2beliefMa/BeliefState.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/ma2beliefMa/BeliefStateSpaceGenerator.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/AFaultTreeEvaluator.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/DFTMetricsComposer.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/DFTModularization.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/FaultEventTransition.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/TimeoutTransition.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/Transition.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/modularizer/FaultTreeTrimmer.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/modularizer/Modularizer.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/modularizer/Module.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/recovery/RecoveryStrategy.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/recovery/minimizer/APartitionRefinementMinimizer.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/recovery/minimizer/ARecoveryAutomatonMinimizer.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/recovery/minimizer/CleanMinimizer.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/recovery/minimizer/ComposedMinimizer.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/recovery/minimizer/FinalStateMinimizer.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/recovery/minimizer/OrthogonalPartitionRefinementMinimizer.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/recovery/minimizer/PartitionRefinementMinimizer.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/synthesizer/ASynthesizer.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/synthesizer/DelegateSynthesizer.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/synthesizer/Schedule2RAConverter.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/util/FaultTreeBuilder.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/util/FaultTreeHelper.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/util/FaultTreeHolder.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/util/RecoveryAutomatonHelper.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/util/RecoveryAutomatonHolder.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/util/StateHolder.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/util/TransitionHolder.java
Labels: quality

#311 Feature/task 310 improve testing of corner
  de.dlr.sc.virsat.model.extension.fdir.test/resources/galileo/csp1.dft
  de.dlr.sc.virsat.model.extension.fdir.test/resources/galileoObs/obsObs2BeDelayed.dft
  de.dlr.sc.virsat.model.extension.fdir.test/resources/galileoRepair/delay1Repair.dft
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/DFTStateTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/DFTEvaluatorTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/synthesizer/BasicSynthesizerTest.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft/analysis/DFTSymmetryChecker.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/DFTState.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/events/IDFTEvent.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/DFTModularization.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/BasicEvent.java
Labels: quality
