Repository virtualsatellite/VirtualSatellite4-FDIR, pull requests merged in 2020-04, with the labels that each got.

#267 Feature/task 266 improve static code a
  .codebeatignore
  .codebeatsettings
  de.dlr.sc.virsat.fdir.branding.ui/.settings/edu.umd.cs.findbugs.core.prefs
  de.dlr.sc.virsat.fdir.branding.ui/src/de/dlr/sc/virsat/fdir/branding/ui/intro/IntroPart.java
  de.dlr.sc.virsat.fdir.core.test/.settings/edu.umd.cs.findbugs.core.prefs
  de.dlr.sc.virsat.fdir.core/.settings/edu.umd.cs.findbugs.core.prefs
  de.dlr.sc.virsat.fdir.galileo.ide/.settings/edu.umd.cs.findbugs.core.prefs
  de.dlr.sc.virsat.fdir.galileo.tests/.settings/edu.umd.cs.findbugs.core.prefs
  de.dlr.sc.virsat.fdir.galileo.ui/.settings/edu.umd.cs.findbugs.core.prefs
  de.dlr.sc.virsat.fdir.galileo/.settings/edu.umd.cs.findbugs.core.prefs
  de.dlr.sc.virsat.fdir.storm.test/.settings/edu.umd.cs.findbugs.core.prefs
  de.dlr.sc.virsat.fdir.storm.test/src/de/dlr/sc/virsat/fdir/storm/runner/StormRunnerTest.java
  de.dlr.sc.virsat.fdir.storm/.settings/edu.umd.cs.findbugs.core.prefs
  de.dlr.sc.virsat.fdir.storm/src/de/dlr/sc/virsat/fdir/storm/docker/DockerHelper.java
  de.dlr.sc.virsat.fdir.storm/src/de/dlr/sc/virsat/fdir/storm/runner/StormScheduler.java
  de.dlr.sc.virsat.fdir.swtbot.test/.settings/edu.umd.cs.findbugs.core.prefs
  de.dlr.sc.virsat.fdir.test/.settings/edu.umd.cs.findbugs.core.prefs
  de.dlr.sc.virsat.model.extension.fdir.experiments/.settings/edu.umd.cs.findbugs.core.prefs
  de.dlr.sc.virsat.model.extension.fdir.experiments/src/de/dlr/sc/virsat/model/extension/fdir/experiments/ASynthesizerExperiment.java
  de.dlr.sc.virsat.model.extension.fdir.test/.settings/edu.umd.cs.findbugs.core.prefs
  de.dlr.sc.virsat.model.extension.fdir.ui/.settings/edu.umd.cs.findbugs.core.prefs
  de.dlr.sc.virsat.model.extension.fdir.ui/plugin.xml
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/VirSatGraphitiLayoutSetup.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/snippet/UiSnippetTableFMECAEntriesFMECAEntry.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/snippet/UiSnippetTableMCSAnalysisMinimumCutSetsCutSet.java
  de.dlr.sc.virsat.model.extension.fdir/.settings/edu.umd.cs.findbugs.core.prefs
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2dft/DFT2BasicDFTConverter.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/DFTState.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/po/ObservationEvent.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/po/PONDDFTSemantics.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/semantics/INodeSemantics.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/semantics/StandardSPARESemantics.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/semantics/VOTESemantics.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/galileo/DFT2GalileoDFT.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/FaultTreeEvaluator.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/StormDFTEvaluator.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/MCSAnalysis.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/synthesizer/ASynthesizer.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/util/FaultTreeHelper.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/util/FaultTreeHolder.java
  maven/pom.xml
  spotbugs-exclude.xml
  spotbugs-include.xml
Labels: build, quality

#270 Cleaned up SWTBot methods - (Task #269)
  de.dlr.sc.virsat.fdir.swtbot.test/src/de/dlr/sc/virsat/fdir/swtbot/test/GraphitiEditorTestCase.java
Labels: quality

#271 Feature/task 268 implement basic po +
  checkStylesDefinition.xml
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/markov/scheduler/MarkovScheduler.java
  de.dlr.sc.virsat.fdir.target/tmodel-src/virsat_fdir_development.tmodel
  de.dlr.sc.virsat.model.extension.fdir.test/resources/galileoObs/obsOr2BeCsp2Delayed.dft
  de.dlr.sc.virsat.model.extension.fdir.test/resources/galileoObsRepair/obsCsp2Repair1.dft
  de.dlr.sc.virsat.model.extension.fdir.test/resources/galileoObsRepair/obsCsp2Repair1Delayed.dft
  de.dlr.sc.virsat.model.extension.fdir.test/resources/galileoObsRepair/obsOr2Csp2Repair1Delayed.dft
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/synthesizer/POSynthesizerTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/validator/StructuralElementInstanceValidatorTest.java
  de.dlr.sc.virsat.model.extension.fdir/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.model.extension.fdir/plugin.xml
  de.dlr.sc.virsat.model.extension.fdir/src-gen/de/dlr/sc/virsat/model/extension/fdir/validator/AFdirValidator.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/po/PONDDFTSemantics.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/ma2beliefMa/BeliefState.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/ma2beliefMa/MA2BeliefMAConverter.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/ClaimAction.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/FreeAction.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/RecoveryAction.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/synthesizer/ASynthesizer.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/synthesizer/BasicSynthesizer.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/synthesizer/POSynthesizer.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/synthesizer/Schedule2RAConverter.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/validator/FdirValidator.java
Labels: feature

#273 Removed sourceforge bin deployment - (Task #272)
  bash/deploy_sourceforge.sh
Labels: build

#274 Fixed left over Core mention in bash script - (Task #272)
  bash/deploy_sourceforge.sh
Labels: build

#275 Copyy & pasted licensing improvements - (Task #265)
  NOTICE.md
  de.dlr.sc.virsat.fdir.branding.ui/about.html
  de.dlr.sc.virsat.fdir.branding.ui/plugin.xml
  de.dlr.sc.virsat.fdir.product/virsat_fdir.product
Labels: quality

#276 Feature/task 263 write chapter on faul
  de.dlr.sc.virsat.fdir.docs.feature/docs/VirSat_FDIR_User_Manual.pdf
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/VirSat_FDIR_User_Manual.adoc
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/faultTrees/AND.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/faultTrees/AND_Diagram.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/faultTrees/BasicEvent.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/faultTrees/BasicEvent_Diagram.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/faultTrees/DELAY.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/faultTrees/DELAY_Diagram.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/faultTrees/FDEP.gif
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/faultTrees/FDEP.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/faultTrees/FDEP_Diagram.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/faultTrees/Fault.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/faultTrees/Fault_Diagram.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/faultTrees/MONITOR.gif
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/faultTrees/MONITOR.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/faultTrees/MONITOR_Diagram.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/faultTrees/OR.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/faultTrees/OR_Diagram.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/faultTrees/PAND.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/faultTrees/PANDI.gif
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/faultTrees/PANDI.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/faultTrees/PANDI_Diagram.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/faultTrees/PAND_Diagram.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/faultTrees/PDEP.gif
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/faultTrees/PDEP.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/faultTrees/PDEP_Diagram.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/faultTrees/POR.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/faultTrees/PORI.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/faultTrees/PORI_Diagram.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/faultTrees/POR_Diagram.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/faultTrees/Propagation.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/faultTrees/Propagation_Diagram.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/faultTrees/RDEP.gif
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/faultTrees/RDEP.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/faultTrees/RDEP_Diagram.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/faultTrees/SAND.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/faultTrees/SAND_Diagram.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/faultTrees/SPARE.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/faultTrees/SPARE_Diagram.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/faultTrees/VOTE.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/faultTrees/VOTE_Diagram.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/faultTrees/diagramEditor.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/faultTrees/openDiagramEditor.png
Labels: quality
