Repository virtualsatellite/VirtualSatellite4-FDIR, pull requests merged in 2020-01, with the labels that each got.

#216 Removed Matrix class - (Task #212)
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/matrix/Matrix.java
Labels: quality

#223 Extracted method getInitialMTTFVector - (Task #219)
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/markov/modelchecker/MarkovModelChecker.java
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/matrix/BellmanMatrix.java
Labels: quality

#225 Feature/task 221 create user handbook
  bash/maven_build.sh
  de.dlr.sc.virsat.fdir.docs.feature/docs/VirSat_FDIR_User_Manual.pdf
  de.dlr.sc.virsat.fdir.docs.feature/pom.xml
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/VirSat_FDIR_User_Manual.adoc
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/title/VirtualSatellite_Modelling_4k.jpg
  de.dlr.sc.virsat.fdir.docs.feature/src/theme/custom-theme.yml
  launchers/VirSat FDIR Build Development (Deploy).launch
  launchers/VirSat FDIR Build Development.launch
  launchers/VirSat FDIR Build Integration (Deploy).launch
  launchers/VirSat FDIR Build Release.launch
  maven/pom.xml
Labels: quality

#226 Modified Markov scheduler to use matrix operations - (Task #211)
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/markov/scheduler/MarkovScheduler.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/synthesizer/BasicSynthesizerTest.java
Labels: quality

#227 Fixed review remarks - (Task #211)
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/markov/scheduler/MarkovScheduler.java
Labels: quality

#229 Fixed NPE - (Task #228)
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/ft/features/faultTreeNodes/FaultTreeNodeDeleteFeature.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/snippet/UiSnippetTableFMECAEntriesFMECAEntry.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/snippet/UiSnippetTableMCSAnalysisMinimumCutSetsCutSet.java
Labels: bug

#232 Updated jacoco maven address - (Task #231)
  build.xml
Labels: build
