Repository virtualsatellite/VirtualSatellite4-FDIR, pull requests merged in 2020-07, with the labels that each got.

#377 Fixed imports - (Task #376)
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/snippet/UiSnippetTableAvailabilityAnalysisAvailabilityCurve.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/snippet/UiSnippetTableDetectabilityAnalysisDetectabilityCurve.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/snippet/UiSnippetTableReliabilityAnalysisReliabilityCurve.java
Labels: build

#379 Upgraded version of maven mojos - (Task #378)
  build.xml
  de.dlr.sc.virsat.fdir.core.test/src/de/dlr/sc/virsat/fdir/core/markov/scheduler/MarkovSchedulerTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/modularizer/ModularizerTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/modularizer/ModuleTest.java
  maven/pom.xml
Labels: build

#380 [User manual] Add sticky note comments usage to manual - (Task #375)
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/VirSat_FDIR_User_Manual.adoc
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/faultTrees/Comment_Sticky_Create.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/faultTrees/Comment_Sticky_Detach.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/faultTrees/Comment_Sticky_Rearrange.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/faultTrees/Comment_Sticky_Reassign.png
Labels: documentation

#374 Increase border margin for auto layout - (Task #320)
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/ft/features/faultTreeNodes/FaultTreeNodeLayoutFeature.java
Labels: comfort/usability

#384 [Fix] revert border margin change
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/ft/features/faultTreeNodes/FaultTreeNodeLayoutFeature.java
Labels: bug, ui

#385 Set border margin for auto layout - (Task #320)
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/ft/FaultTreeLayoutConnector.java
Labels: comfort/usability, ui

#386 Add sticky notes in RecoveryAutomatonDiagram - (Task #383)
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/comments/CommentAddFeature.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/comments/CommentMoveFeature.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/comments/CommentUtil.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/ft/features/faultTreeNodes/FaultTreeNodeLayoutFeature.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/ft/features/faultTreeNodes/FaultTreeNodeMoveFeature.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/ra/RecoveryAutomatonFeatureProvider.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/ra/features/states/StateLayoutFeature.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/ra/features/states/StateMoveFeature.java
Labels: comfort/usability, feature

#388 Feature/task 160 compensation entry of
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/model/FMECATest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/model/FaultTreeTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/util/FaultTreeHolderTest.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/BasicEvent.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/FMECA.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/FMECAEntry.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/Fault.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/FaultEvent.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/FaultTree.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/util/FaultTreeHolder.java
Labels: bug

#387 Add Quick Start Tutorial - (Task #314)
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/VirSat_FDIR_User_Manual.adoc
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/tutorial/Tutorial_Add_BasicEvents.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/tutorial/Tutorial_Add_Concept.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/tutorial/Tutorial_Add_ConfigurationTree.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/tutorial/Tutorial_Add_ElementConfiguration.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/tutorial/Tutorial_Add_Equation.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/tutorial/Tutorial_Add_FDIR_Parameters.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/tutorial/Tutorial_Add_Fault.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/tutorial/Tutorial_AutoLayout.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/tutorial/Tutorial_Availability_Analysis.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/tutorial/Tutorial_BasicEvent_Equation.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/tutorial/Tutorial_Create_Project.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/tutorial/Tutorial_FDIR_Parameters.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/tutorial/Tutorial_FaultTree_Modelling.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/tutorial/Tutorial_Open_DiagramEditor.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/tutorial/Tutorial_Rename_ElementConfiguration.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/tutorial/Tutorial_Rename_System.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/tutorial/Tutorial_Save_Concept.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/tutorial/Tutorial_Save_Fault.png
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/images/tutorial/Tutorial_Severity_Settings.png
Labels: documentation
