Repository virtualsatellite/VirtualSatellite4-FDIR, pull requests merged in 2020-02, with the labels that each got.

#238 Updated deployment process to sourceforge
  .travis.yml
  bash/deploy_sourceforge.sh
  bash/ssh-add-password.sh
  id_ed25519.enc
Labels: build

#240 Fixes to verify authors log and diff #239
  bash/verify_commit_authors.sh
Labels: bug, build

#241 Feature/task 235 support repair semant
  de.dlr.sc.virsat.model.extension.fdir.test/resources/galileoRepair/csp2Repair2BadPrimary.dft
  de.dlr.sc.virsat.model.extension.fdir.test/resources/galileoRepair/csp2Repair2BadSpare.dft
  de.dlr.sc.virsat.model.extension.fdir.test/resources/galileoRepair/fdep1Csp2Repair1.dft
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/converter/GalileoDFT2DFTTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/DFT2MAConverterTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/DFTEvaluatorTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/recovery/minimizer/OrthogonalPartitionRefinementMinimizerTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/synthesizer/BasicSynthesizerTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/util/RecoveryAutomatonHelperTest.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/FreeAction.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/modularizer/Module.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/recovery/minimizer/OrthogonalPartitionRefinementMinimizer.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/recovery/minimizer/PartitionRefinementMinimizer.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/util/FaultTreeHelper.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/util/RecoveryAutomatonHelper.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/util/RecoveryAutomatonHolder.java
Labels: feature

#244 Simplified XText grammar - (Task #243)
  de.dlr.sc.virsat.fdir.galileo.ide/src-gen/de/dlr/sc/virsat/fdir/galileo/ide/contentassist/antlr/DftParser.java
  de.dlr.sc.virsat.fdir.galileo.ide/src-gen/de/dlr/sc/virsat/fdir/galileo/ide/contentassist/antlr/internal/InternalDft.g
  de.dlr.sc.virsat.fdir.galileo.ide/src-gen/de/dlr/sc/virsat/fdir/galileo/ide/contentassist/antlr/internal/InternalDft.tokens
  de.dlr.sc.virsat.fdir.galileo.ide/src-gen/de/dlr/sc/virsat/fdir/galileo/ide/contentassist/antlr/internal/InternalDftLexer.java
  de.dlr.sc.virsat.fdir.galileo.ide/src-gen/de/dlr/sc/virsat/fdir/galileo/ide/contentassist/antlr/internal/InternalDftParser.java
  de.dlr.sc.virsat.fdir.galileo.ui/src-gen/de/dlr/sc/virsat/fdir/galileo/ui/contentassist/AbstractDftProposalProvider.java
  de.dlr.sc.virsat.fdir.galileo/model/generated/Dft.ecore
  de.dlr.sc.virsat.fdir.galileo/model/generated/Dft.genmodel
  de.dlr.sc.virsat.fdir.galileo/src-gen/de/dlr/sc/virsat/fdir/galileo/Dft.xtextbin
  de.dlr.sc.virsat.fdir.galileo/src-gen/de/dlr/sc/virsat/fdir/galileo/dft/Delay.java
  de.dlr.sc.virsat.fdir.galileo/src-gen/de/dlr/sc/virsat/fdir/galileo/dft/DftFactory.java
  de.dlr.sc.virsat.fdir.galileo/src-gen/de/dlr/sc/virsat/fdir/galileo/dft/DftPackage.java
  de.dlr.sc.virsat.fdir.galileo/src-gen/de/dlr/sc/virsat/fdir/galileo/dft/Parametrized.java
  de.dlr.sc.virsat.fdir.galileo/src-gen/de/dlr/sc/virsat/fdir/galileo/dft/Rdep.java
  de.dlr.sc.virsat.fdir.galileo/src-gen/de/dlr/sc/virsat/fdir/galileo/dft/impl/DelayImpl.java
  de.dlr.sc.virsat.fdir.galileo/src-gen/de/dlr/sc/virsat/fdir/galileo/dft/impl/DftFactoryImpl.java
  de.dlr.sc.virsat.fdir.galileo/src-gen/de/dlr/sc/virsat/fdir/galileo/dft/impl/DftPackageImpl.java
  de.dlr.sc.virsat.fdir.galileo/src-gen/de/dlr/sc/virsat/fdir/galileo/dft/impl/ParametrizedImpl.java
  de.dlr.sc.virsat.fdir.galileo/src-gen/de/dlr/sc/virsat/fdir/galileo/dft/impl/RdepImpl.java
  de.dlr.sc.virsat.fdir.galileo/src-gen/de/dlr/sc/virsat/fdir/galileo/dft/util/DftAdapterFactory.java
  de.dlr.sc.virsat.fdir.galileo/src-gen/de/dlr/sc/virsat/fdir/galileo/dft/util/DftSwitch.java
  de.dlr.sc.virsat.fdir.galileo/src-gen/de/dlr/sc/virsat/fdir/galileo/parser/antlr/internal/InternalDft.g
  de.dlr.sc.virsat.fdir.galileo/src-gen/de/dlr/sc/virsat/fdir/galileo/parser/antlr/internal/InternalDft.tokens
  de.dlr.sc.virsat.fdir.galileo/src-gen/de/dlr/sc/virsat/fdir/galileo/parser/antlr/internal/InternalDftLexer.java
  de.dlr.sc.virsat.fdir.galileo/src-gen/de/dlr/sc/virsat/fdir/galileo/parser/antlr/internal/InternalDftParser.java
  de.dlr.sc.virsat.fdir.galileo/src-gen/de/dlr/sc/virsat/fdir/galileo/serializer/DftSemanticSequencer.java
  de.dlr.sc.virsat.fdir.galileo/src-gen/de/dlr/sc/virsat/fdir/galileo/services/DftGrammarAccess.java
  de.dlr.sc.virsat.fdir.galileo/src/de/dlr/sc/virsat/fdir/galileo/Dft.xtext
  de.dlr.sc.virsat.model.extension.fdir.experiments/src/de/dlr/sc/virsat/model/extension/fdir/experiments/ASynthesizerExperiment.java
  de.dlr.sc.virsat.model.extension.fdir.test/resources/galileo/delay1.dft
  de.dlr.sc.virsat.model.extension.fdir.test/resources/galileo/rdep1.dft
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/converter/DFT2GalileoDFTTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/converter/GalileoDFT2DFTTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/test/ATestCase.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/wizards/ExportGalileoDFTWizard.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/wizards/ImportGalileoDFTWizard.java
  de.dlr.sc.virsat.model.extension.fdir/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/galileo/DFT2GalileoDFT.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/galileo/GalileoDFT2DFT.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/StormDFTEvaluator.java
Labels: feature

#247 Created basic introduction - (Task #246)
  de.dlr.sc.virsat.fdir.docs.feature/src/docs/VirSat_FDIR_User_Manual.adoc
Labels: quality

#248 Feature/task 245 expand minimization s
  de.dlr.sc.virsat.fdir.core.test/src/de/dlr/sc/virsat/fdir/core/markov/scheduler/MarkovSchedulerTest.java
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/markov/modelchecker/MarkovModelChecker.java
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/markov/scheduler/MarkovScheduler.java
  de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/matrix/BellmanMatrix.java
  de.dlr.sc.virsat.model.extension.fdir.test/resources/galileo/pand2ColdSpare1Shared.dft
  de.dlr.sc.virsat.model.extension.fdir.test/resources/galileoObs/obsOr2Csp2Delayed.dft
  de.dlr.sc.virsat.model.extension.fdir.test/resources/galileoObs/obsOr2Csp2ObsBE.dft
  de.dlr.sc.virsat.model.extension.fdir.test/resources/galileoObs/obsOr2Csp2ObsBEUnreliable.dft
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/DFTEvaluatorTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/recovery/minimizer/OrthogonalPartitionRefinementMinimizerTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/synthesizer/BasicSynthesizerTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/synthesizer/POSynthesizerTest.java
  de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/synthesizer/Schedule2RAConverterTest.java
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/wizards/ImportGalileoDFTWizard.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2dft/DFT2BasicDFTConverter.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/DFT2MAConverter.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/DFTState.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/FaultEvent.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/po/PODFTState.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/po/PONDDFTSemantics.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/semantics/DFTSemantics.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/semantics/NDSPARESemantics.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/semantics/PORSemantics.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/semantics/StandardSPARESemantics.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/galileo/GalileoDFT2DFT.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/modularizer/FaultTreeNodePlus.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/modularizer/Module.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/recovery/minimizer/OrthogonalPartitionRefinementMinimizer.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/synthesizer/ASynthesizer.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/synthesizer/POSynthesizer.java
  de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/synthesizer/Schedule2RAConverter.java
Labels: feature

#253 Feature/task 236 swt bot graphiti
  .travis.yml
  de.dlr.sc.virsat.fdir.swtbot.test/.checkstyle
  de.dlr.sc.virsat.fdir.swtbot.test/.classpath
  de.dlr.sc.virsat.fdir.swtbot.test/.project
  de.dlr.sc.virsat.fdir.swtbot.test/.settings/org.eclipse.jdt.core.prefs
  de.dlr.sc.virsat.fdir.swtbot.test/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.fdir.swtbot.test/about.html
  de.dlr.sc.virsat.fdir.swtbot.test/build.properties
  de.dlr.sc.virsat.fdir.swtbot.test/pom.xml
  de.dlr.sc.virsat.fdir.swtbot.test/src/de/dlr/sc/virsat/fdir/swtbot/test/GraphitiEditorTestCase.java
  de.dlr.sc.virsat.fdir.swtbot.test/src/de/dlr/sc/virsat/fdir/swtbot/test/ProjectUiAllTests.java
  de.dlr.sc.virsat.fdir.target/tmodel-src/fdir_dependencies.tmodel
  de.dlr.sc.virsat.fdir.target/virsat_fdir_development.target
  de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/handler/AOpenInDiagramEdiorHandler.java
  pom.xml
Labels: quality

#255 Added: "AND Gate" test case for Graphiti Diagram Editor - (Task #251)
  de.dlr.sc.virsat.fdir.swtbot.test/src/de/dlr/sc/virsat/fdir/swtbot/test/GraphitiEditorTestCase.java
Labels: quality

#258 Feature/task 257 swt bot tests broken
  de.dlr.sc.virsat.fdir.swtbot.test/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.fdir.swtbot.test/src/de/dlr/sc/virsat/fdir/swtbot/test/GraphitiEditorTestCase.java
Labels: bug, build

#260 Feature/task 249 dependencies issue in p2
  de.dlr.sc.virsat.fdir.docs.feature/docs/VirSat_FDIR_User_Manual.pdf
  de.dlr.sc.virsat.fdir.galileo.feature/feature.xml
  de.dlr.sc.virsat.fdir.galileo.ide/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.fdir.galileo/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.fdir.p2updatesite/category.xml
  de.dlr.sc.virsat.fdir.product/virsat_fdir.product
  de.dlr.sc.virsat.fdir.storm.feature/.project
  de.dlr.sc.virsat.fdir.storm.feature/.settings/org.eclipse.core.resources.prefs
  de.dlr.sc.virsat.fdir.storm.feature/.settings/org.eclipse.jdt.core.prefs
  de.dlr.sc.virsat.fdir.storm.feature/.settings/org.eclipse.m2e.core.prefs
  de.dlr.sc.virsat.fdir.storm.feature/.settings/org.eclipse.mylyn.team.ui.prefs
  de.dlr.sc.virsat.fdir.storm.feature/build.properties
  de.dlr.sc.virsat.fdir.storm.feature/feature.properties
  de.dlr.sc.virsat.fdir.storm.feature/feature.xml
  de.dlr.sc.virsat.fdir.storm.feature/pom.xml
  de.dlr.sc.virsat.fdir.swtbot.test/.classpath
  de.dlr.sc.virsat.fdir.target/virsat_fdir_development.target
  de.dlr.sc.virsat.model.extension.fdir.feature/feature.xml
  pom.xml
Labels: build
